#!/bin/bash
source /etc/tizen-platform.conf
MOUNT_DIRECTORY=$1
find $MOUNT_DIRECTORY -type d | xargs chsmack -a '*' -t
find $MOUNT_DIRECTORY -type f | xargs chsmack -a '*'
find $MOUNT_DIRECTORY -type d | xargs chmod 770
find $MOUNT_DIRECTORY -type f | xargs chmod 660
find $MOUNT_DIRECTORY -type d | xargs chown root:priv_externalstorage
find $MOUNT_DIRECTORY -type f | xargs chown root:priv_externalstorage
